### ISSUE TITLE
Hyper Protect DBaaS for PostgreSQL uuid-ossp

### ISSUE THREAD

**Issue by rjmanzer** [ibm-cloud-docs/hyper-protect-dbaas-for-postgresql#3]
uuid-ossp extension is not working in Hyper Protect. Tried to migrate from existing PostgreSQL and got an error because creating functions with uuid-ossp requires super user permission and the admin in Hyper Protect is not a super user. So am unable to migrate to Hyper Protect without a lot of painful changes.

**Comment by wenygao** [comment]
@rjmanzer ,

In the next DBaaS release, some extensions including uuid-ossp can be created by the Hyper Protect DBaaS admin without super user permission. So you can retry later once the new DBaaS release is alive on production.

**Comment by PanLiyuan** [comment]
Hi @rjmanzer, thanks for the feedback. You can find new feature updates in the [What's new](https://cloud.ibm.com/docs/hyper-protect-dbaas-for-postgresql?topic=hyper-protect-dbaas-for-postgresql-what-new) topic when a release is out. I'll close this issue if you have no further questions or comments.
